INSERT INTO sign_category (sign_category_id, name,parent_id) VALUES(0, '交通标志图解',null);
INSERT INTO sign_category (sign_category_id, name,parent_id) VALUES(1, '指示标志',0);
INSERT INTO sign_category (sign_category_id, name,parent_id) VALUES(2, '指示标线',0);
INSERT INTO sign_category (sign_category_id, name,parent_id) VALUES(3, '指路标志',0);
INSERT INTO sign_category (sign_category_id, name,parent_id) VALUES(4, '禁令标志',0);
INSERT INTO sign_category (sign_category_id, name,parent_id) VALUES(5, '禁止标线',0);
INSERT INTO sign_category (sign_category_id, name,parent_id) VALUES(6, '警告标志',0);
INSERT INTO sign_category (sign_category_id, name,parent_id) VALUES(7, '警告标线',0);
INSERT INTO sign_category (sign_category_id, name,parent_id) VALUES(8, '辅助标志',0);
INSERT INTO sign_category (sign_category_id, name,parent_id) VALUES(9, '旅游区标志',0);
INSERT INTO sign_category (sign_category_id, name,parent_id) VALUES(10, '道路安全标识',0);
INSERT INTO sign_category (sign_category_id, name,parent_id) VALUES(11, '道路施工安全设施设置示例',0);
INSERT INTO sign_category (sign_category_id, name,parent_id) VALUES(12, '新版交警手势',null);
INSERT INTO sign_category (sign_category_id, name,parent_id) VALUES(13, '事故大全图解',null);

INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(1, 1, '直行', 's1.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(2, 1, '向左转弯 ', 's2.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(3, 1, '向右转弯 ', 's3.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(4, 1, '直行和向左转弯 ', 's4.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(5, 1, '直行和向右转弯 ', 's5.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(6, 1, '向左和向右转弯 ', 's6.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(7, 1, '靠右侧道路行驶', 's7.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(8, 1, '靠左侧道路行驶 ', 's8.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(9, 1, '立交直行和左转弯行驶 ', 's9.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(10, 1, '立交直行和右转弯行驶 ', 's10.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(11, 1, '环岛行驶 ', 's11.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(12, 1, '步行 ', 's12.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(13, 1, '鸣喇叭 ', 's13.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(14, 1, '最低限速 ', 's14.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(15, 1, '单行路向左或向右 ', 's15.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(16, 1, '单行路 直行 ', 's16.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(17, 1, '干路先行 ', 's17.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(18, 1, '会车先行 ', 's18.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(19, 1, '人行横道 ', 's19.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(20, 1, '右转车道 ', 's20.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(21, 1, '直行车道 ', 's21.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(22, 1, '直行和右转合用车道 ', 's22.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(23, 1, '分向行驶车道 ', 's23.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(24, 1, '公交线路专用车道', 's24.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(25, 1, '机动车行驶 ', 's25.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(26, 1, '机动车车道', 's26.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(27, 1, '非机动车行驶 ', 's27.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(28, 1, '非机动车车道 ', 's28.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(29, 1, '允许掉头 ', 's29.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(30, 2, '双向两车道路面中心线 ', 'x1.jpg');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(31, 2, '车行道分界线 ', 'x2.jpg');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(32, 2, '车行道分界线 ', 'x3.jpg');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(33, 2, '车行道边缘线', 'x4.jpg');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(34, 2, '车行道边缘线 ', 'x5.jpg');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(35, 2, '边缘线的尺寸　单位：cm ', 'x6.jpg');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(36, 2, '左弯待转区线 ', 'x7.jpg');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(37, 2, '左转弯导向线', 'x8.jpg');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(38, 2, '人行横道(正交) ', 'x9.jpg');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(39, 2, '人行横道(斜交) ', 'x10.jpg');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(40, 2, '人行横道(信号灯路口) ', 'x11.jpg');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(41, 2, '人行横道预告标示 ', 'x12.jpg');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(42, 2, '车距确认 ', 'x13.jpg');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(43, 2, '车距确认线尺寸 ', 'x14.jpg');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(44, 2, '直接式出口标线 ', 'x15.jpg');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(45, 2, '平行式出口标线 ', 'x16.jpg');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(46, 2, '直接式入口标线 ', 'x17.jpg');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(47, 2, '平行式入口标线 ', 'x18.jpg');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(48, 2, '平行式停车位 ', 'x19.jpg');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(49, 2, '倾斜式停车位', 'x20.jpg');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(50, 2, '垂直式停车位 ', 'x21.jpg');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(51, 2, '出租车专用待客停车位 ', '22.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(52, 2, '出租车专用上下客车位', '23.jpg');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(53, 2, '残疾人专用车辆车位 ', '24.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(54, 2, '非机动车专用停车位', '25.jpg');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(55, 2, '港湾式停靠站 ', '26.jpg');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(56, 2, '港湾式停靠站 ', '27.jpg');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(57, 2, '收费岛地面标线 ', '28.jpg');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(58, 2, '行车速度≤40km/h时的导向箭头 ', '29.jpg');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(59, 2, '行车速度在60-80km/h时的导向箭头', '30.jpg');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(60, 2, '最高速度 ', '31.jpg');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(61, 2, '最低限速', '32.jpg');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(62, 2, '大型车 ', '33.jpg');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(63, 2, '小型车 ', '34.jpg');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(64, 2, '超车道 ', '35.jpg');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(65, 2, '非机动车车道标记', '36.jpg');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(66, 3, '地名', 'r1.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(67, 3, '著名地点 ', 'r2.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(68, 3, '行政区划分界 ', 'r3.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(69, 3, '道路管理分界 ', 'r4.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(70, 3, '国道编号', 'r5.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(71, 3, '省道编号 ', 'r6.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(72, 3, '县道编号 ', 'r7.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(73, 3, '行驶方向 ', 'r8_1.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(74, 3, '行驶方向 ', 'r9.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(75, 3, '行驶方向', 'r10.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(76, 3, '行驶方向 ', 'r11.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(77, 3, '行驶方向 ', 'r12.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(78, 3, '行驶方向 ', 'r13.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(79, 3, '行驶方向 ', 'r14.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(80, 3, '行驶方向 ', 'r15.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(81, 3, '互通式立交', 'r16.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(82, 3, '交叉路口预告 ', 'r17.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(83, 3, '十字交叉路口 ', 'r18.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(84, 3, '十字交叉路口 ', 'r19.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(85, 3, '十字交叉路口 ', 'r20.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(86, 3, '十字交叉路口 ', 'r21.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(87, 3, '丁字交叉路口', 'r22.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(88, 3, '丁字交叉路口 ', 'r23.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(89, 3, '环形交叉路口 ', 'r24.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(90, 3, '环形交叉路口 ', 'r25.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(91, 3, '交叉路口预告 ', 'r26.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(92, 3, '互通式立交 ', 'r27.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(93, 3, '互通式立交 ', 'r28.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(94, 3, '互通式立交 ', 'r29.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(95, 3, '分岔处 ', 'r30.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(96, 3, '地点距离标志', 'r31.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(97, 3, '地点识别标志 ', 'r32.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(98, 3, '地点识别标志', 'r33.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(99, 3, '地点识别标志 ', 'r34.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(100, 3, '地点识别标志 ', 'r35.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(101, 3, '地点识别标志 ', 'r36.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(102, 3, '地点识别标志', 'r37.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(103, 3, '地点识别标志 ', 'r38.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(104, 3, '地点识别标志 ', 'r39.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(105, 3, '地点识别标志 ', 'r40.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(106, 3, '地点识别标志 ', 'r41.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(107, 3, '地点识别标志 ', 'r42.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(108, 3, '告示牌 ', 'r43.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(109, 3, '告示牌 ', 'r44.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(110, 3, '告示牌 ', 'r45.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(111, 3, '告示牌 ', 'r46.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(112, 3, '告示牌 ', 'r47.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(113, 3, '告示牌 ', 'r48.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(114, 3, '告示牌 ', 'r49.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(115, 3, '告示牌 ', 'r50.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(116, 3, '告示牌 ', 'r51.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(117, 3, '告示牌 ', 'r52.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(118, 3, '停车场 ', 'r53.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(119, 3, '停车场 ', 'r54.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(120, 3, '停车场 ', 'r55.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(121, 3, '避车道 ', 'r56.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(122, 3, '人行天桥  人行地下通道', 'r57.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(123, 3, '绕行标志 ', 'r58.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(124, 3, '绕行标志 ', 'r59.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(125, 3, '绕行标志 ', 'r60.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(126, 3, '此路不通 ', 'r61.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(127, 3, '残疾人专用设施 ', 'r62.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(128, 3, '起点 ', '10.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(129, 3, '终点预告 ', '11.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(130, 3, '终点提示 ', '12.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(131, 3, '终点', '13.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(132, 3, '下一出口 ', '14.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(133, 3, '下一出口 ', '15.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(134, 3, '出口编号预告 ', '16.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(135, 3, '出口预告 ', '17.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(136, 3, '出口预告 ', '18.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(137, 3, '出口预告 ', '19.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(138, 3, '出口预告 ', '20.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(139, 3, '出口预告', '41.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(140, 3, '出口预告', '22.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(141, 3, '出口 ', '23.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(142, 3, '出口 ', '24.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(143, 3, '出口 ', '25.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(144, 3, '出口 ', '26.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(145, 3, '地点方向 ', '27.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(146, 3, '地点方向 ', '28.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(147, 3, '地点方向 ', '29.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(148, 3, '地点方向 ', '3320080715011824.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(149, 3, '地点方向 ', '34.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(150, 3, '地点方向 ', '35.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(151, 3, '地点方向 ', '36.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(152, 3, '地点距离 ', '37.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(153, 3, '收费站预告 ', '38.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(154, 3, '收费站预告 ', '39.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(155, 3, '收费站预告 ', '40.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(156, 3, '收费站', '4120080715012321.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(157, 3, '紧急电话 ', '42.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(158, 3, '电话立置指示 ', '43.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(159, 3, '电话立置指示 ', '44.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(160, 3, '加油站', '45.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(161, 3, '紧急停车带 ', '46.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(162, 3, '服务区预告 ', '47.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(163, 3, '服务区预告 ', '48.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(164, 3, '服务区预告 ', '49.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(165, 3, '服务区预告 ', '50.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(166, 3, '停车区预告 ', '5120080715012857.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(167, 3, '停车区预告 ', '52.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(168, 3, '停车区预告 ', '53.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(169, 3, '停车场 ', '54.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(170, 3, '停车场 ', '55.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(171, 3, '停车场 ', '56.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(172, 3, '爬坡车道 ', '0910.jpg');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(173, 3, '爬坡车道 ', '58.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(174, 3, '爬坡车道 ', '59.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(175, 3, '爬坡车道 ', '60.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(176, 3, '车距确认 ', '61.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(177, 3, '车距确认 ', '62.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(178, 3, '车距确认 ', '63.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(179, 3, '车距确认 ', '64.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(180, 3, '车距确认', '65.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(181, 3, '道路交通信息 ', '66.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(182, 3, '道路交通信息 ', '67.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(183, 3, '道路交通信息 ', '68.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(184, 3, '里程牌 ', '69.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(185, 3, '百米牌 ', '70.jpg');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(186, 3, '分流 ', '71.jpg');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(187, 3, '合流 ', '72.jpg');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(188, 3, '线形诱导标基本单元 ', '73.jpg');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(189, 3, '基本单元组合使用 ', '74.jpg');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(190, 3, '右侧通行 ', '75.jpg');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(191, 3, '左侧通行 ', '76.jpg');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(192, 3, '两侧通行 ', '77.jpg');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(194, 9, '旅游区方向 ', 'l1.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(195, 9, '旅游区距离 ', 'l2.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(196, 9, '问询处 ', 'l3.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(197, 9, '徒步 ', 'l4.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(198, 9, '索道 ', 'l5.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(199, 9, '野营地 ', 'l6.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(200, 9, '营火 ', 'l7.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(201, 9, '游戏场 ', 'l8.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(202, 9, '骑马 ', 'l9.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(203, 9, '钓鱼 ', 'l10.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(204, 9, '高尔夫球 ', 'l11.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(205, 9, '潜水 ', 'l12.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(206, 9, '游泳 ', 'l13.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(207, 9, '划船 ', 'l14.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(208, 9, '冬季浏览区 ', 'l15.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(209, 9, '滑雪 ', 'l16.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(210, 9, '滑冰 ', 'l17.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(212, 4, '禁止通行 ', 'j1.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(213, 4, '禁止驶入 ', 'j2.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(214, 4, '禁止机动车驶入', 'j3.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(215, 4, '禁止载货汽车驶入', 'j4.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(216, 4, '禁止三轮机动车驶入', 'j5.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(217, 4, '禁止大型客车驶入', 'j6.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(218, 4, '禁止小型客车驶入', 'j7.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(219, 4, '禁止汽车拖、挂车驶入', 'j8.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(220, 4, '禁止拖拉机驶入', 'j9.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(221, 4, '禁止农用车驶入', 'j10.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(222, 4, '禁止二轮摩托车驶入', 'j11.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(223, 4, '禁止某两种车驶入', 'j12.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(224, 4, '禁止非机动车进入', 'j13.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(225, 4, '禁止畜力车进入', 'j14.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(226, 4, '禁止人力货运三轮车进入', 'j15.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(227, 4, '禁止人力客运三轮车进入', 'j16.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(228, 4, '禁止人力车进入', 'j17.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(229, 4, '禁止骑自行车下坡 ', 'j18.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(230, 4, '禁止骑自行车上坡 ', 'j19.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(231, 4, '禁止行人进入', 'j20.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(232, 4, '禁止向左转弯 ', 'j21.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(233, 4, '禁止向右转弯 ', 'j22.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(234, 4, '禁止直行 ', 'j23.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(235, 4, '禁止向左向右转弯 ', 'j24.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(236, 4, '禁止直行和向左转弯', 'j25.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(237, 4, '禁止直行和向右转弯 ', 'j26.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(238, 4, '禁止掉头 ', 'j27.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(239, 4, '禁止超车 ', 'j28.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(240, 4, '解除禁止超车', 'j29.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(241, 4, '禁止车辆临时或长时停放 ', 'j30.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(242, 4, '禁止车辆长时停放 ', 'j31.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(243, 4, '禁止鸣喇叭 ', 'j32.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(244, 4, '限制宽度 ', 'j33.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(245, 4, '限制高度 ', 'j34.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(246, 4, '限制质量 ', 'j35.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(247, 4, '限制轴重 ', 'j36.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(248, 4, '限制速度 ', 'j37.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(249, 4, '解除限制速度', 'j38.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(250, 4, '停车检查 ', 'j39.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(251, 4, '停车让行 ', 'j40.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(252, 4, '减速让行 ', 'j41.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(253, 4, '会车让行 ', 'j42.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(254, 4, '禁止运输危险物品车辆驶入标志   ', 'j43.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(255, 5, '中心黄色双实线 ', 'x31.jpg');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(256, 5, '中心黄色虚实线', 'x32.jpg');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(257, 5, '三车道标线 ', 'x33.jpg');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(258, 5, '计算行车速度V>60km/h，斜率i≥1', 'x34.jpg');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(259, 5, '计算行车速度V>60km/h，L≥100', 'x35.jpg');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(260, 5, '计算行车速度V>60km/h，L≥100', 'x36.jpg');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(261, 5, '计算行车速度V>60km/h，L≥100', 'x37.jpg');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(262, 5, '计算行车速度V>60km/h，L≥100', 'x38.jpg');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(263, 5, '禁止变换车道线 ', 'x39.jpg');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(264, 5, '禁止路边长时停放车辆线', 'x40.jpg');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(265, 5, '禁止路边临时或长时停放车辆线', 'x41.jpg');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(266, 5, '信号灯路口的停止线 ', 'x42.jpg');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(267, 5, '停止线的尺寸　单位:cm ', 'x43.jpg');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(268, 5, '停车让行线 ', 'x44.jpg');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(269, 5, '减速让行线 ', 'x45.jpg');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(270, 5, '非机动车禁驶区标线 ', 'x46.jpg');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(271, 5, '禁驶区标线尺寸　单位:cm ', 'x47.jpg');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(272, 5, '复杂行驶条件丁字路口导流线 ', 'x48.jpg');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(273, 5, '复杂行驶条件十字路口导流线 ', 'x49.jpg');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(274, 5, '斜交丁字路口导流线 ', 'x50.jpg');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(275, 5, '不规则路口导流线 ', 'x51.jpg');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(276, 5, 'Y形路口导流线 ', 'x52.jpg');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(277, 5, '支路口主干道相交路口导流线', 'x53.jpg');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(278, 5, '中心圈 ', 'x54.jpg');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(279, 5, '中心圈 ', 'x55.jpg');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(280, 5, '网状线 ', 'x56.jpg');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(281, 5, '简化网状线 ', 'x57.jpg');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(282, 5, '专用车道线', 'x58.jpg');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(283, 5, '禁止掉头', 'x59.jpg');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(284, 6, '十字交叉', 'j1.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(285, 6, 'T形交叉 ', 'j2.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(286, 6, 'T形交叉', 'j3.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(287, 6, 'T形交叉 ', 'j4.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(288, 6, 'Y形交叉', 'j5.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(289, 6, '环形交叉 ', 'j6.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(290, 6, '向左急弯路 ', 'j7.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(291, 6, '向右急弯路 ', 'j8.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(292, 6, '反向弯路 ', 'j9.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(293, 6, '连续弯路 ', 'j10.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(294, 6, '上陡坡 ', 'j11.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(295, 6, '下陡坡 ', 'j12.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(296, 6, '两侧变窄 ', 'j13.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(297, 6, '右侧变窄', 'j14.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(298, 6, '左侧变窄 ', 'j15.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(299, 6, '窄桥 ', 'j16.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(300, 6, '双向交通 ', 'j17.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(301, 6, '注意行人 ', 'j18.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(302, 6, '注意儿童 ', 'j19.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(303, 6, '注意牲畜 ', 'j20.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(304, 6, '注意信号灯 ', 'j21.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(305, 6, '注意落石 ', 'j23.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(306, 6, '注意横风 ', 'j24.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(307, 6, '易滑 ', 'j25.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(308, 6, '傍山险路 ', 'j26.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(309, 6, '傍山险路 ', 'j27.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(310, 6, '堤坝路 ', 'j28.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(311, 6, '堤坝路', 'j29.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(312, 6, '村庄 ', 'j30.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(313, 6, '隧道 ', 'j31.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(314, 6, '渡口', 'j32.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(315, 6, '驼峰桥 ', 'j33.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(316, 6, '路面不平 ', 'j34.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(317, 6, '过水路面 ', 'j35.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(318, 6, '有人看守铁路道口', 'j36.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(319, 6, '无人看守铁路道口 ', 'j37.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(320, 6, '注意非机动车 ', 'j38.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(321, 6, '事故易发路段 ', 'j39.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(322, 6, '慢行 ', 'j40.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(323, 6, '左右绕行 ', 'j41.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(324, 6, '左侧绕行 ', 'j42.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(325, 6, '右侧绕行 ', 'j43.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(326, 6, '施工 ', 'j44.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(327, 6, '注意危险 ', 'j45.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(328, 6, '斜杠符号 ', 'j46.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(329, 6, '斜杠符号 ', 'j47.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(330, 6, '斜杠符号 ', 'j48.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(331, 6, '叉形符号 ', 'j49.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(332, 7, '三车道缩减为双车道 ', 'x60.jpg');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(333, 7, '四车道缩减为双车道 ', 'x61.jpg');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(334, 7, '四车道缩减为三车道 ', 'x62.jpg');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(335, 7, '四车道缩减为两车道 ', 'x63.jpg');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(336, 7, '三车道斑马线过渡 ', 'x64.jpg');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(337, 7, '双向两车道改变为双向四车道 ', 'x65.jpg');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(338, 7, '双车道中间有障碍 ', 'x66.jpg');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(339, 7, '四车道中间有障碍 ', 'x67.jpg');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(340, 7, '同方向二车道中间有障碍 ', 'x68.jpg');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(341, 7, '铁路平交道口标线 ', 'x69.jpg');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(342, 7, '减速标线 ', 'x70.jpg');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(343, 7, '收费广场减速标线设置例 ', 'x71.jpg');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(344, 7, '立面标记', 'x72.jpg');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(345, 8, '时间范围 ', 'b1.jpg');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(346, 8, '时间范围 ', 'b2.jpg');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(347, 8, '除公共汽车外 ', 'b3.jpg');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(348, 8, '机动车 ', 'b4.jpg');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(349, 8, '货车', 'b5.jpg');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(350, 8, '货车、拖拉机 ', 'b6.jpg');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(351, 8, '向前200M ', 'b7.jpg');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(352, 8, '向左100M ', 'b8.jpg');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(353, 8, '向左、向右各50M', 'b9.jpg');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(354, 8, '向右100M ', 'b10.jpg');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(355, 8, '某区域内 ', 'b11.jpg');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(356, 8, '学校 ', 'b12.jpg');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(357, 8, '海关 ', 'b13.jpg');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(358, 8, '事故 ', 'b14.jpg');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(359, 8, '坍方 ', 'b15.jpg');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(360, 8, '组合 ', 'b16.jpg');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(361, 10, '施工路栏 ', 's1.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(362, 10, '施工路栏 ', 's2.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(363, 10, '锥形交通标 ', 's3.gif');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(364, 10, '锥形交通标 ', 's4.jpg');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(365, 10, '道口标柱 ', 's5.jpg');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(366, 10, '前方施工 ', 's6.jpg');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(367, 10, '前方施工 ', 's7.jpg');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(368, 10, '道路施工 ', 's8.jpg');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(369, 10, '道路封闭 ', 's9.jpg');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(370, 10, '道路封闭 ', 's10.jpg');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(371, 10, '道路封闭 ', 's11.jpg');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(372, 10, '右道封闭 ', 's12.jpg');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(373, 10, '右道封闭', 's13.jpg');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(374, 10, ' 右道封闭', 's14.jpg');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(375, 10, '左道封闭 ', 's15.jpg');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(376, 10, '左道封闭', 's16.jpg');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(377, 10, '左道封闭', 's17.jpg');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(378, 10, '中间封闭 ', 's18.jpg');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(379, 10, '中间封闭', 's19.jpg');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(380, 10, '中间封闭', 's20.jpg');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(381, 10, '车辆慢行', 's21.jpg');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(382, 10, '向左行驶', 's22.jpg');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(383, 10, '向右行驶', 's23.jpg');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(384, 10, '向左改道 ', 's24.jpg');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(385, 10, '向右改道', 's25.jpg');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(386, 10, '移动性施工标志 ', 's26.jpg');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(387, 11, '示例1　双车道路面局部施工时设施布设例 ', 's1.jpg');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(388, 11, '示例2　视距不良双车道路面局部施工时设施', 's2.jpg');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(389, 11, '示例3　改道施工时设施布设例 ', 's3.jpg');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(390, 11, '示例4　四车道以上道路一侧路面施工时设施', 's4.jpg');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(391, 11, '示例5　同向车道中有一条车道路面施工时设', 's5.jpg');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(392, 11, '示例6　同向车道中有两条车道以上路面施工', 's6.jpg');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(393, 11, '示例7　高速公路一侧施工，利用中央分隔带', 's7.jpg');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(394, 11, '示例8　市区道路交叉口，有一侧路面施工时', 's8.jpg');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(395, 11, '示例9　市区道路交叉口中心线附近施工时的', 's9.jpg');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(396, 11, '示例10　市区道路交叉口中心线附近施工时', 's10.jpg');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(397, 11, '示例11　市区道路两侧施工只能单向行驶时', 's11.jpg');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(398, 11, '示例12　高速公路出口三角地带附近施工时', 's12.jpg');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(399, 11, '示例13　高速公路出口减速车道施工时的设', 's13.jpg');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(400, 11, '示例14　高速公路入口加速车道边缘施工时', 's14.jpg');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(401, 11, '示例15　高速公路入口加速车道施工时的设', 's15.jpg');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(402, 12, '（一）停止信号\n手势示意：不准前方车辆通', 'jjss_1.jpg');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(403, 12, '（二）直行信号\n手势示意：准许右方直行的', 'jjss_2.jpg');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(404, 12, '（三）左转弯信号\n手势示意：准许车辆左转', 'jjss_3.jpg');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(405, 12, '（四）左转弯待转信号\n手势示意：准许交警', 'jjss_4.jpg');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(406, 12, '（五）右转弯信号\n手势示意：准许交警右方', 'jjss_5.jpg');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(407, 12, '（六）变道信号\n手势示意：车辆腾空指定的', 'jjss_6.jpg');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(408, 12, '（七）减速慢行\n手势示意：车辆减速慢行。', 'jjss_7.jpg');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(409, 12, '（八）停车信号\n手势示意：车辆靠边停车', 'jjss_8.jpg');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(410, 13, '追撞前车尾部的，图中所示，均为A车全责', '1.jpg');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(411, 13, '变更车道时，未让正在该车道内行驶的车先行的，图中所示，均为A车全责', '2.jpg');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(412, 13, '通过没有交通信号灯或者交通警察指挥的交叉路口时，未让交通标志、交通标线规定优先通行的一方先行的，图中所示，均为A车全责', '3.jpg');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(413, 13, '通过没有交通信号灯控制或者交通警察指挥的交叉路口时，在交通标志、标线未规定优先通行的路口，未让右方道路的来车先行的，图中所示，均为A车全责', '4.jpg');
INSERT INTO sign_content (sign_content_id, category_id, name, picture) VALUES(414, 13, '通过没有交通信号灯控制或者交通警察指挥的交叉路口，遇相对方向来车，左转弯车未让直行车先行的，图中所示，均为A车全责', '5.jpg');